apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: sc1-3a
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
